name: Full CI/CD Workflow

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Build and push Docker images
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-backend:latest ./dokodine-backend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-backend:latest
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-frontend:latest ./dokodine-frontend
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-frontend:latest

    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy fastapi-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-backend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8000

    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy nextjs-frontend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dokodine-frontend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 3000
