name: "On Merge"

on:
    push:
        branches: [ main, dev ]

jobs:
    develop:
        name: "on_merge Dev"
        if: ${{ github.base_ref == 'dev' }}
        uses: ./.github/workflows/merge_deploy.yml
        permissions:
            contents: read
        secrets: inherit
        with:
            environment_name: dev
    
    prod:
        name: "on_merge Prod"
        if: ${{ github.base_ref == 'main' }}
        uses: ./.github/workflows/merge_deploy.yml
        permissions:
            contents: read
        secrets: inherit
        with:
            environment_name: prod