name: "Terraform Plan"

on:
  pull_request:
    branches: [main, dev]

env:
  TF_CLOUD_ORGANIZATION: "${{ vars.TF_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./terraform"

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
      tf_workspace: ${{ steps.set-env.outputs.tf_workspace }}
      service_name: ${{ steps.set-env.outputs.service_name }}
      gar_repo: ${{ steps.set-env.outputs.repository_id }}
    steps:
    - name: Set environment variables based on branch
      id: set-env
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "env_name=prod" >> $GITHUB_OUTPUT
          echo "tf_workspace=${{ secrets.TF_WORKSPACE_PROD }}" >> $GITHUB_OUTPUT
          echo "service_name=${{ vars.SERVICE_NAME_PROD }}" >> $GITHUB_OUTPUT
          echo "gar_repo=${{ vars.GAR_REPO_PROD }}" >> $GITHUB_OUTPUT
        else
          echo "env_name=dev" >> $GITHUB_OUTPUT
          echo "tf_workspace=${{ secrets.TF_WORKSPACE_DEV }}" >> $GITHUB_OUTPUT
          echo "service_name=${{ vars.SERVICE_NAME_DEV }}" >> $GITHUB_OUTPUT
          echo "gar_repo=${{ vars.GAR_REPO_DEV }}" >> $GITHUB_OUTPUT
        fi

  # lint-and-test:
  #   name: "Lint and Test"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         pip install flake8 pytest
  #     - name: Run linter
  #       run: flake8 .
  #     - name: Run tests
  #       run: pytest

  build-and-test:
    needs: set-environment
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t dokodine-backend:${{ github.sha }} .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name dokodine-backend-container dokodine-backend:${{ github.sha }}

  terraform:
    needs: [build-and-test, set-environment]
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0 #hashicorp/setup-terraform@v2
        id: plan-upload
        with:
          workspace: ${{ needs.set-environment.outputs.tf_workspace }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: ${{ needs.set-environment.outputs.tf_workspace }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true
        env:
          TF_VAR_service_name: ${{ needs.set-environment.outputs.service_name }}
          TF_VAR_gar_repo: ${{ needs.set-environment.outputs.gar_repo }}


      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

      - name: Update PR
        uses: actions/github-script@v6
        id: plan-comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
            });
            const output = `#### Terraform Cloud Plan Output
               \`\`\`
               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
               \`\`\`
               [Terraform Cloud Plan](${{ steps.plan-run.outputs.run_link }})
               `;
            // 3. Delete previous comment so PR timeline makes sense
            if (botComment) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              });
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
